- name: Publish role
  hosts: localhost
  gather_facts: no
  vars:
    webserver_root: "/scratch/ansible-role-docs"
  tasks:
    - name: debug
      debug:
          msg: "role archive is {{role_archive}}"
    - name: create roles directory in webserver_root
      file:
        path: "{{ webserver_root }}/roles"
        state: directory
        mode: 0755

    - name: publish new role to roles dir in webserver_root
      # role_archive path is specified through environment vars
      copy: src={{role_archive}} dest={{ webserver_root }}/roles/
