oci_database_autonomous_exadata_infrastructure: oci_autonomous_exadata_infrastructure
oci_database_autonomous_exadata_infrastructure_shape: oci_autonomous_exadata_infrastructure_shape

# override load_balancer to loadbalancer to avoid conflicts with old modules
oci_load_balancer: oci_loadbalancer_load_balancer
oci_load_balancer_backend: oci_loadbalancer_backend
oci_load_balancer_backend_health: oci_loadbalancer_backend_health
oci_load_balancer_backend_set: oci_loadbalancer_backend_set
oci_load_balancer_backend_set_health: oci_loadbalancer_backend_set_health
oci_load_balancer_certificate: oci_loadbalancer_certificate
oci_load_balancer_health_checker: oci_loadbalancer_health_checker
oci_load_balancer_health: oci_loadbalancer_health
oci_load_balancer_hostname: oci_loadbalancer_hostname
oci_load_balancer_listener: oci_loadbalancer_listener
oci_load_balancer_path_route_set: oci_loadbalancer_path_route_set
oci_load_balancer_policy: oci_loadbalancer_policy
oci_load_balancer_protocol: oci_loadbalancer_protocol
oci_load_balancer_rule_set: oci_loadbalancer_rule_set
oci_load_balancer_shape: oci_loadbalancer_shape
