# this configuration is used by the script that copies codegenConfig and pom.xml info from
# the python SDK into our ansible repo to keep it up to date on features
# these blacklists are used to skip certain features or entires modules (services) that
# ansible does not yet support

# there may be services that don't support yet that break generation
# so this is a way to explicitly skip including those modules
# The blacklist entry can be any substring of the `module` element
# in the python-sdk pom.xml
python_sdk_pom_modules_blacklist:
  - pom-fixups
  # has a codegen error that needs to be fixed
  - cims
  # - key_management
  # the following services are completely gated by ifdefs so without those it is empty and therefore invalid
  - vault
  - secrets
  - data_safe

# a list of either features IDs or enabled groups that are enabled in the
# Python SDK but we do not want to enable in ansible
python_sdk_features_blacklist:
   # identity assemble effective tag set
  - 'udx-1837'
  # CreateOAuthClientCredentials conflicts with create user 
  - 'udx-2098'

python_sdk_spec_version_overrides: []
