---

#Copyright © 2021, Oracle and/or its affiliates.
#The Universal Permissive License (UPL), Version 1.0

#playbook: database_discovery
#file: discover.yml

# Validate input variables
- name: Validate input variables
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  pre_tasks:

    - assert:
        that: 
          - tag_based is defined
          - tag_based|bool == True or tag_based|bool == False
        fail_msg: "tag_based is required and should be boolean"

    - assert:
        that: 
          - compartment_id is defined
          - tag is defined
        fail_msg: "compartment_id and tag is required"
      when: 
        - tag_based
    
    - assert:
        that: 
          - db_system_id is defined
        fail_msg: "db_system_id is required list and should be non-empty"
      when: 
        - not tag_based

    - assert:
        that: 
          - patch_operation is defined
          - patch_operation|length > 0
        fail_msg: "patch_opeartion is required and should be non-empty"

- name: Patch DB using OCID(s) - Non Tag based
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  gather_facts: true
  tasks:
    - name: Loop db patching - Non tag based
      include_role:
        name: patch_db
      vars:
        db_system_ocid: "{{ item }}"
      with_items: "{{ db_system_id }}"
      when: not tag_based

- name: Patch DB using OCID(s) - Tag based
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Get db system ocids
      include_role:
        name: db_discovery
      vars:  
        compartment_ocid: "{{ compartment_id }}"
      when: tag_based

    - name: Loop db patching - Tag based
      include_role:
        name: patch_db
      vars:
        db_system_ocid: "{{ item }}"
      with_items: "{{ db_system_id }}"
      when: tag_based
      
...
