---
- name: Main | Import PRE_FLIGHT.YML task file
  include_tasks: pre_flight.yml
  tags: ['mushop_vcn', 'mushop_vcn_preflight', 'preflight']

- name: Main | Import VCN.YML task file
  import_tasks: vcn.yml
  tags: ['mushop_vcn']

- name: Main | Import POLICIES.YML task file
  import_tasks: policies.yml
  tags: ['mushop_vcn', 'policies']
