---
- name: Policy | Create policy for mushop object storage
  oci_identity_policy:
    name: "{{ env }}-{{ region }}-mushop-object-family"
    compartment_id: "{{ vcn_reg.vcn.compartment_id }}"
    tenancy: "{{ oci_tenancy_ocid }}"
    region: "{{ region }}"
    freeform_tags: "{{ oci_ansible_free_default_tags }}"
    description: 'Policy created by Ansible for MuShop Basic object storage'
    statements:
      - "Allow service objectstorage-{{ region }} to manage object-family in compartment id {{ vcn_reg.vcn.compartment_id }}"
