---

#Copyright © 2021, Oracle and/or its affiliates.
#The Universal Permissive License (UPL), Version 1.0

#role: patch_db
#file: defaults/main.yml

### Database system variables

# Get database system details
#db_system_details: "{{ db_system_facts | json_query('db_systems[].{display_name: display_name,compartment_id: compartment_id, id: id, lifecycle_state: lifecycle_state, shape: shape, database_edition: database_edition, version: version,last_patch_history_entry_id: last_patch_history_entry_id, defined_tags: defined_tags }') }}"
db_system_details: "{{ db_system_facts | json_query('db_systems[].{display_name: display_name,compartment_id: compartment_id, id: id, lifecycle_state: lifecycle_state, shape: shape, database_edition: database_edition, version: version,last_patch_history_entry_id: last_patch_history_entry_id, defined_tags: defined_tags }') }}"

# Check database system is available
db_system_available: "{% if db_system_facts |json_query('db_systems[].lifecycle_state | [0]') == 'AVAILABLE' %}True{% else %}False{% endif %}"
#db_system_available: "{% if db_system_facts.db_systems[0].lifecycle_state == 'AVAILABLE' %}True{% else %}False{% endif %}"

# Get database system state
db_system_state: "{{ db_system_facts | json_query('db_systems[].lifecycle_state | [0]')}}"
#db_system_state: "{{ db_system_facts.db_systems[0].lifecycle_state }}"

# Get database system patch PRECHECK status
db_system_patch_precheck_status: "{% if db_system_precheck_status |json_query('db_system_patch_history_entries[].lifecycle_state | [0]') == 'SUCCEEDED' %}True{% else %}False{% endif %}"

# Get database system patch APPLY status
db_system_patch_apply_status: "{% if db_system_apply_status |json_query('db_system_patch_history_entries[].lifecycle_state | [0]') == 'SUCCEEDED' %}True{% else %}False{% endif %}"


### Database home variables

# Check database home is available
db_home_available: "{% if db_home_facts |json_query('db_homes[].lifecycle_state | [0]') == 'AVAILABLE' %}True{% else %}False{% endif %}"

# Get database home details
db_home_details: "{{ db_home_facts | json_query('db_homes[].{compartment_id:compartment_id,display_name: display_name,id: id, lifecycle_state: lifecycle_state, last_patch_history_entry_id: last_patch_history_entry_id }') }}"

# Get database home state
db_home_state: "{{ db_home_facts | json_query('db_homes[].lifecycle_state | [0]')}}"

# Get database home last patch history id
db_home_patch_history_entry_id: "{{ db_home_facts | json_query('db_homes[].last_patch_history_entry_id | [0]') }}"

# Get database home PRECHECK status
db_home_patch_precheck_status: "{% if db_home_precheck_status |json_query('db_home_patch_history_entries[].lifecycle_state | [0]') == 'SUCCEEDED' %}True{% else %}False{% endif %}"

# Get database home APPLY status
db_home_patch_apply_status: "{% if db_home_apply_status |json_query('db_home_patch_history_entries[].lifecycle_state | [0]') == 'SUCCEEDED' %}True{% else %}False{% endif %}"