---
################################################################
# This playbook is intended to validate a list of expressions
# that are required at the global level.  It should be included
# in every playbook at the top level as an import.
#
################################################################
- hosts: localhost
  gather_facts: False
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/envs/{{ env }}.yml"
    - "../../vars/regions/{{ region }}.yml"
  tasks:
    - name: Confirmation Playbook | Confirmation block
      tags: ['always']
      when: not ( auto_confirm | default(False) | bool )
      block:
        - name: Confirmation Playbook | Get user confirmation
          pause:
            prompt: "###########################################\n\
                     # \n\
                     # Ansible_env: {{ env }}\n\
                     # OCI Tenancy: {{ oci_tenancy_ocid }}\n\
                     # OCI Region: {{ region }}\n\
                     # Auto-confirm: {{ auto_confirm }}\n\
                     # \n\
                     ##########################################\n\
                     Please confirm the above settings are correct by typing 'yes'"
          register: confirmation

        - name: Confirmation Playbook | Fail without confirmation
          fail:
            msg: "Env/Region confirmation failed"
          when: confirmation.user_input | lower != 'yes'

        - name: Confirmation Playbook | Set Confirmation fact
          set_fact:
            auto_confirm: True
          when: confirmation.user_input | lower == 'yes'
      # End Block
