---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Autonomous Database usage example
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars:
    display_name: "always_free_adb"
    db_name: "alwaysfreeadb" # (Maximum 14 alphanumeric characters)
   
    # the following settings are inherent to Always Free ADBs and cannot be scaled
    data_storage_size_in_tbs: 1  # always free ADB will have 0.02 TB (20 GB) of storage but API requires value of >= 1 TB
    cpu_core_count: 1

    #########################################
    # *Note* - Override the following variables based on your tenancy
    # or set a valid value for the corresponding environment variable
    # Please refer to module documentation for sample values for
    # variables
    #########################################
    compartment_ocid: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
    admin_password: "{{ lookup('env', 'SAMPLE_ADMIN_PASSWORD') }}" # sample value, admin_password: 'BEstr0ng_#11'

  tasks:
    - block:

        - name: Check pre-requisites
          fail:
            msg: "Environment variable {{item}} not set. Please declare an environment variable with an appropriate value for the sample to work."
          when: item not in ansible_env
          with_items:
            - "SAMPLE_COMPARTMENT_OCID"
            - "SAMPLE_ADMIN_PASSWORD"

        - name: Create a new Always Free Autonomous Database
          oci_database_autonomous_database:
              compartment_id: "{{ compartment_ocid }}"
              cpu_core_count: "{{ cpu_core_count }}"
              display_name: "{{ display_name }}"
              admin_password: "{{ admin_password }}"
              db_name: "{{ db_name }}"
              data_storage_size_in_tbs: "{{ data_storage_size_in_tbs }}"
              is_free_tier: true
              state: 'present'
          register: result

        - set_fact:
             autonomous_database_id: "{{ result.autonomous_database.id }}"

        - assert:
            that:
              - result.autonomous_database.lifecycle_state == "AVAILABLE"

    # List Autonomous Databases filtered by Display Name
        - name: List All Autonomous Databases in a compartment, filtered by Display Name
          oci_database_autonomous_database_facts:
             compartment_id: "{{ compartment_ocid }}"
             display_name: '{{ display_name }}'
          register: result

        - name: Assert that specified Autonomous Database is listed
          assert:
             that:
                - result.autonomous_databases[0].display_name == display_name

    # Stop Autonomous Databases
        - name: Stop an Autonomous Database
          oci_database_autonomous_database_actions:
             autonomous_database_id: "{{ autonomous_database_id }}"
             action: 'stop'
          register: result

        - name: Assert that specified Autonomous Database is stopped
          assert:
             that:
                - result.autonomous_database.lifecycle_state == 'STOPPED'

    # Start Autonomous Databases
        - name: Start Autonomous Database
          oci_database_autonomous_database_actions:
             autonomous_database_id: "{{ autonomous_database_id }}"
             action: 'start'
          register: result

        - name: Assert that specified Autonomous Database is started and available
          assert:
             that:
                - result.autonomous_database.lifecycle_state == 'AVAILABLE'

    # Get a specific Autonomous Database
        - name: Get a specific Autonomous Database's facts
          oci_database_autonomous_database_facts:
             autonomous_database_id: "{{ autonomous_database_id }}"
          register: result
        - debug: # print facts retrieved about the Autonomous Database
              msg: "{{result}}"
        - name: Assert that specified Autonomous Database is listed
          assert:
             that:
                - result.autonomous_databases[0].display_name == display_name

        - import_tasks: teardown.yaml

      rescue:

        - import_tasks: teardown.yaml
          ignore_errors: yes

        - fail:
            msg: "The sample execution failed."
