---
- name: Get a specific namespace
  oci_object_storage_namespace_facts:
  register: oci_tenancy_namespace

- name: Object Storage | Create default object storage bucket
  oci_object_storage_bucket:
    name: "{{ env }}-{{ os.mushop_bucket_name }}"
    tenancy: "{{ oci_tenancy_ocid }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    compartment_id: "{{ oci_tenancy_ocid }}"
    freeform_tags: "{{ oci_ansible_free_default_tags }}"

- name: Object Storage | Create media object storage bucket
  oci_object_storage_bucket:
    name: "{{ env }}-{{ os.media_bucket_name }}"
    public_access_type: "{{ os.media_bucket_public_access_type }}"
    tenancy: "{{ oci_tenancy_ocid }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    compartment_id: "{{ oci_tenancy_ocid }}"
    freeform_tags: "{{ oci_ansible_free_default_tags }}"

- name: Create Storage | Create object storage bucket policy
  oci_object_storage_object_lifecycle_policy:
    tenancy: "{{ oci_tenancy_ocid }}"
    region: "{{ region }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    bucket_name: "{{ env }}-{{ os.mushop_bucket_name }}"
    items:
      - name: 'mushop-delete-deploy-assets-rule'
        action: DELETE
        time_amount: 1
        time_unit: DAYS
        is_enabled: true
