---
- name: Object Storage | Create temporary mushop directory
  file:
    state: directory
    path: "{{ mushop_tmpdir.path }}/mushop-basic-stack"

- name: Object Storage | Download and extract mushop website code
  unarchive:
    src: "{{ mushop_release_url }}"
    dest: "{{ mushop_tmpdir.path }}/mushop-basic-stack"
    remote_src: yes

- name: Object Storage | Push files into object storage
  oci_object_storage_object:
    tenancy: "{{ oci_tenancy_ocid }}"
    bucket_name: "{{ env }}-{{ os.mushop_bucket_name }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    object_name: "{{ file.name }}"
    src: "{{ file.src }}"
  loop_control:
    loop_var: file
    label: "{{ file.name }}"
  loop:
    - src: "{{ mushop_tmpdir.path }}/{{ env }}-{{ region }}-mushop-atp_{{ atp.db_name }}_wallet.zip"
      name: 'mushop_atp_wallet'
    - src: "{{ playbook_dir }}/roles/mushop_infra/files/atp_mushop_catalogue.sql"
      name: 'catalogue_sql_script'
    - src: "{{ playbook_dir }}/roles/mushop_infra/files/httpd.conf"
      name: 'apache_conf'
    - src: "{{ playbook_dir }}/roles/mushop_infra/files/entrypoint.sh"
      name: 'entrypoint'
    - src: "{{ mushop_tmpdir.path }}/mushop-basic-stack/scripts/mushop-basic.tar.gz"
      name: 'mushop_basic'

- name: Object Storage | Push files into media object storage
  oci_object_storage_object:
    tenancy: "{{ oci_tenancy_ocid }}"
    bucket_name: "{{ env }}-{{ os.media_bucket_name }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    content_type: 'image/png'
    cache_control: 'max-age=604800, public, no-transform'
    object_name: "{{ image | basename }}"
    src: "{{ image }}"
  with_fileglob: "{{ mushop_tmpdir.path }}/mushop-basic-stack/images/*.png"
  loop_control:
    loop_var: image
  tags: ['os_media_upload']

- name: Object Storage | Remove temporary directory from filesystem
  file:
    path: "{{ mushop_tmpdir.path }}"
    state: absent
