---
- name: Object Storage Preauth | Create Preauthenticated MuShop requests
  oci_object_storage_preauthenticated_request:
    tenancy: "{{ oci_tenancy_ocid }}"
    bucket_name: "{{ env }}-{{ os.mushop_bucket_name }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    name: "{{ par.par_name }}"
    access_type: 'ObjectRead'
    time_expires: "{{ '%Y-%m-%dT%H:%M:%S%z'
                    | strftime( ( ansible_date_time.epoch | int ) + ( 60 * 60 * 24 ) )
                   }}"
    object_name: "{{ par.object_name }}"
  loop_control:
    label: "{{ par.par_name }}"
    loop_var: 'par'
  loop:
    - par_name: 'mushop_wallet_preauth'
      object_name: 'mushop_atp_wallet'
    - par_name: 'catalogue_sql_script_preauth'
      object_name: 'catalogue_sql_script'
    - par_name: 'apache_conf_preauth'
      object_name: 'apache_conf'
    - par_name: 'entrypoint_preauth'
      object_name: 'entrypoint'
    - par_name: 'mushop_lite_preauth'
      object_name: 'mushop_basic'
  register: mushop_par_reg

- name: Object Storage Preauth | Create Preauthenticated media requests
  oci_object_storage_preauthenticated_request:
    tenancy: "{{ oci_tenancy_ocid }}"
    bucket_name: "{{ env }}-{{ os.media_bucket_name }}"
    namespace_name: "{{ oci_tenancy_namespace.namespace }}"
    name: 'mushop_assets_preauth'
    time_expires: "{{ '%Y-%m-%dT%H:%M:%S%z'
                    | strftime( ( ansible_date_time.epoch | int ) + ( 60 * 60 * 24 ) )
                   }}"
    access_type: 'AnyObjectWrite'
  register: media_par_reg

- name: Object Storage Preauth | Generate dictionary with PAR info
  set_fact:
    preauth_facts_dict: "{{ preauth_facts_dict | default({})
                          | combine(
                            {
                              par_object.name : 'https://objectstorage.'
                                                + region
                                                + '.oraclecloud.com'
                                                + par_object.access_uri
                            }
                          )
                         }}"
  loop: "{{ mushop_par_reg.results | map(attribute='preauthenticated_request') | list
            + [media_par_reg.preauthenticated_request] }}"
  loop_control:
    label: "{{ par_object.name }}"
    loop_var: 'par_object'
