FROM quay.io/ansible/default-test-container:1.10.1

WORKDIR /root/

ADD ansible_collections/oracle/oci/tests/runner/requirements/units.txt .

RUN pip2.7 install -r units.txt && \
    pip3.5 install -r units.txt && \
    pip3.6 install -r units.txt && \
    pip3.7 install -r units.txt && \
    pip3.8 install -r units.txt

