---
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Sample for creating Image
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    # common networking definitions
    quad_zero_route: "0.0.0.0/0"
    TCP_protocol: "6"
    SSH_port: "22"

    vcn_name: "customimgvcn"
    vcn_cidr_block: "10.0.0.0/16"
    vcn_dns_label: "customimgvcn"

    ig_name: "customimgigforcustomimgvcn"
    route_table_name: "customimgrt"
    # route all internet access to our Internet Gateway
    route_table_rules:
        - cidr_block: "{{ quad_zero_route }}"
          network_entity_id: "{{ ig_id }}"

    subnet_cidr: "10.0.1.0/24"
    subnet_name: "customimgsubnet"
    subnet_dns_label: "customimgsubnet"

    public_instance_egress_security_rules:
      # Allow all connections outside
      - destination: "{{ quad_zero_route }}"
        protocol: "all"

    public_instance_ingress_security_rules:
      # Allow incoming SSH connections
      - source: "{{ quad_zero_route }}"
        protocol: "{{ TCP_protocol }}"
        tcp_options:
          destination_port_range:
            min: "{{ SSH_port }}"
            max: "{{ SSH_port }}"

    securitylist_name: "customimgsl"

    instance_shape: "{{ lookup('env', 'SAMPLE_INSTANCE_SHAPE') | default('VM.Standard2.1', true) }}"
    instance_hostname: "customimginstance"
    #########################################
    # Tenancy specific configuration
    # *Note* - Override the following variables based on your tenancy
    # or set a valid value for the corresponding environment variable
    #########################################
    instance_ad: "{{ lookup('env', 'SAMPLE_AD_NAME') }}"
    instance_display_name: "customimginstance"
    instance_compartment: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
    # find image ocids per region here: https://docs.cloud.oracle.com/iaas/images/image/501c6e22-4dc6-4e99-b045-cae47aae343f/
    instance_image: "{{ lookup('env', 'SAMPLE_IMAGE_OCID') }}"

    display_name: "{{ lookup('env', 'SAMPLE_DISPLAY_NAME') | default('customimage', true) }}"

  tasks:
    - block:
        - import_tasks: setup.yaml

        - name: Launch an instance
          oci_compute_instance:
            availability_domain: "{{ instance_ad }}"
            compartment_id: "{{ instance_compartment }}"
            name: "customimg_test_instance"
            image_id: "{{ instance_image }}"
            shape: "{{ instance_shape }}"
            create_vnic_details:
                assign_public_ip: True
                hostname_label: "{{ instance_hostname }}"
                subnet_id: "{{ instance_subnet_id }}"
            metadata:
                ssh_authorized_keys: "{{ lookup('file',  my_test_public_key ) }}"
          register: result

        - name: Print instance details
          debug:
            msg: "Launched a new instance {{ result }}"
        - set_fact:
            instance_id: "{{result.instance.id }}"

        - name: Print the public ip of the newly launched instance
          debug:
            msg: "Public IP of launched instance {{ result.instance.primary_public_ip }}"

        - name: Create image with required parameters
          oci_compute_image:
            compartment_id: "{{ instance_compartment }}"
            freeform_tags: {'Department': 'OCI'}
            instance_id: '{{ instance_id }}'
            launch_mode: 'PARAVIRTUALIZED'
            state: 'present'
          register: result
        - set_fact:
            image: "{{ result.image }}"
            image_id: "{{ result.image.id }}"

        - import_tasks: teardown.yaml

      rescue:
        - import_tasks: teardown.yaml
          ignore_errors: yes

        - fail:
            msg: "{{ ansible_failed_result }}"