---
################################################################
## This playbook is intended to deploy a given service into
## a given OCI tenancy.
## Example:
##   ansible-playbook playbooks/deploy_service.yml
##     -e "env=free region=us-ashburn-1 service=mushop"
##
#################################################################

# Run common validation steps
- import_playbook: validation/common.yml
  tags:
    - validate_common
    - validate

- import_playbook: validation/tenancy.yml
  tags:
    - validate_tenancy
    - validate

- import_playbook: validation/confirmation.yml
  tags:
    - validate_confirmation
    - validate

- hosts: localhost
  collections:
    - oracle.oci
  gather_facts: True
  vars_files:
    - "../vars/defaults.yml"
    - "../vars/envs/{{ env }}.yml"
    - "../vars/regions/{{ region }}.yml"
    - "../vars/services/mushop.yml"
  pre_tasks:
    - name: Playbook | Include variables for relevant environment
      include_vars:
        dir: '../vars/oci'
        extensions: ['yaml', 'yml']
  tasks:
    - name: Playbook | Include VCN role
      include_role:
        name: 'mushop_vcn'
        apply:
          tags:
            - mushop_vcn

    - name: Playbook | Include Infra role
      include_role:
        name: 'mushop_infra'
        apply:
          tags:
            - mushop_infra

  post_tasks:
    - name: Playbook | Provide debug output
      debug:
        msg:
          - "Ansible run complete.  Deployment Info:"
          - "  Load balancer public address: http://{{ (oci_lb_reg.load_balancer.ip_addresses
                                                       | selectattr('is_public', 'equalto', True)
                                                       | first).ip_address
                                                     }}"
          - "  ATP Database Password: {{ atp_password }}"
