# playbook for cleaning up resources in teh AnsibleTestIntegrationCompartment1

- name: Clean the resources     # only looking at block volume resources right now
  hosts: localhost
  vars:
    test_compartment_id: "ocid1.compartment.oc1..aaaaaaaa7tlbhw5sjnbf7u7eyonsfjt737773ptgj66nlnsyr3teglev2bla"
    tformat: '%Y-%m-%dT%H:%M:%S.%f+%W:%U'
    hours: 3    # number of hours to be excluded from now

  tasks:
    - name: Fetch the block volumes in the compartment
      oracle.oci.oci_blockstorage_volume_facts:
        compartment_id: "{{ test_compartment_id }}"
        lifecycle_state: "AVAILABLE"
      register: block_volumes

    - name: Delete all the block volumes which was created more than 3 hours from now
      oracle.oci.oci_blockstorage_volume:
        volume_id: "{{ item.id }}"
        state: "absent"
      loop: "{{ block_volumes.volumes }}"
      ignore_errors: yes
      when:
        - (( now(utc=True) - item.time_created|to_datetime("{{ tformat }}") ).total_seconds() / 3600) > hours
