---
- name : List summary of existing buckets in OCI object storage
  connection: local
  hosts: localhost
  tasks:
    - name: List bucket facts
      oci_bucket_facts:
         namespace_name: 'bmcs-dex-us-ashburn-1'
         compartment_id: 'ocid1.compartment.oc1..aaaaaaaa7tlbhw5sjnbf7u7eyonsfjt737773ptgj66nlnsyr3teglev2bla'
      register: result
    - name: Dump result
      debug:
        msg: '{{result}}'

