---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: List objects from all the buckets
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    # common vars
    sample_bucket_name: "sample_bucket"
    sample_object_name: "sample_object"

    #########################################
    # Tenancy specific configuration
    # *Note* - Override the following variables based on your tenancy
    # or set a valid value for the corresponding environment variable 
    #########################################
    compartment_id: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
    namespace_name: "{{ lookup('env', 'SAMPLE_OBJECT_NS_NAME') }}"

  tasks:
    - name: Get all the buckets in the namespace
      oci_object_storage_bucket_facts:
        namespace_name: "{{ namespace_name }}"
        compartment_id: "{{ compartment_id }}"
      register: ocibuckets

    - name: Get all objects from all the buckets
      oci_object_storage_object_facts:
        namespace_name: "{{ namespace_name }}"
        bucket_name: "{{ item.name }}"
      with_items: "{{ ocibuckets.buckets }}"
      register: output
    - name: Print objects list
      debug:
        msg: 'Bucket: {{item.item.name}}, Objects: {{item.objects}}'
      loop: "{{output.results}}"
      loop_control:
        label: "{{item.item.name}}"

#     The above variable, output, contains key "results" which is a list of result of individual invocation through
#     with_items. Each result has "item" key that has the bucket's details and the "objects" key that contains all the
#     objects within that bucket:
#      output:
#      {
#       results:
#        [
#          {
#            item:{},
#            objects: []
#          }
#        ]
#      }
