---
- name: ATP | Generate ATP Password
  no_log: True
  set_fact:
    atp_password: "{{ lookup('password', '/tmp/passwordfile length=29') }}"

- name: ATP | Create or update Autonomous Database
  oci_database_autonomous_database:
    tenancy: "{{ oci_tenancy_ocid }}"
    region: "{{ region }}"
    compartment_id: "{{ vcn_reg.vcn.compartment_id }}"
    freeform_tags: "{{ oci_ansible_free_default_tags }}"
    display_name: "{{ env }}-{{ region }}-mushop-atp"
    db_name: "{{ atp.db_name }}"
    db_version: "{{ atp.db_version }}"
    db_workload: "{{ atp.db_workload }}"
    cpu_core_count: "{{ atp.cpu_core_count }}"
    data_storage_size_in_tbs: "{{ atp.data_storage_size_in_tbs }}"
    is_free_tier: "{{ atp.is_free_tier }}"
    admin_password: "{{ atp_password }}"
    license_model: 'LICENSE_INCLUDED'
    wait: False
  register: oci_atp_reg

  # We wait separately to avoid task timeout
- name: ATP | Wait for Autonomous database to be provisioned
  oci_database_autonomous_database_facts:
    region: "{{ region }}"
    tenancy: "{{ oci_tenancy_ocid }}"
    autonomous_database_id: "{{ oci_atp_reg.autonomous_database.id }}"
  register: atp_wait
  until: atp_wait.autonomous_databases.0.lifecycle_state == 'AVAILABLE'
  retries: 60 # Retry for 30 minutes
  delay: 30
  failed_when: atp_wait.autonomous_databases | length > 1

- name: create temporary build directory
  tempfile:
    state: directory
    suffix: mushop
  register: mushop_tmpdir
  changed_when: False

- name: Create ATP | Download database wallet password
  oci_database_autonomous_database_actions:
    tenancy: "{{ oci_tenancy_ocid }}"
    region: "{{ region }}"
    autonomous_database_id: "{{ oci_atp_reg.autonomous_database.id }}"
    password: "{{ atp_password }}"
    action: generate_autonomous_database_wallet
    wallet_file: "{{ mushop_tmpdir.path }}/{{ env }}-{{ region }}-mushop-atp_{{ atp.db_name }}_wallet.zip"
